import { writeFileSync, existsSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';

export interface InitOptions {
  projectId: string;
  domain: string;
  language: string;
  region: string;
  publisherAdapter: 'markdown-files' | 'blogposts-ts' | 'wordpress';
  outputPath: string;
  overwrite?: boolean;
}

export interface PlatformsScaffoldResult {
  configWritten: boolean;
  mcpWritten: boolean;
  envExampleWritten: boolean;
}

export function generateConfig(options: InitOptions): boolean {
  if (existsSync(options.outputPath) && options.overwrite === false) {
    return false;
  }

  const dir = dirname(options.outputPath);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }

  const publisherConfig = getPublisherConfig(options.publisherAdapter);

  const config = {
    projectId: options.projectId,
    domain: options.domain,
    language: options.language,
    region: options.region,
    dbPath: './data/seo-engine.db',
    publisher: {
      adapter: options.publisherAdapter,
      config: publisherConfig,
    },
    googleAds: {
      clientId: '',
      clientSecret: '',
      developerToken: '',
      refreshToken: '',
      customerId: '',
    },
    dataforseo: {
      login: '',
      password: '',
    },
    platforms: {
      bingWmt: {
        siteUrl: `https://${options.domain}/`,
        apiKey: '',
      },
    },
  };

  writeFileSync(options.outputPath, JSON.stringify(config, null, 2) + '\n', 'utf-8');
  return true;
}

/**
 * Generate per-project .mcp.json + .env.platforms.example for the 4-platform
 * analytics stack (GA4, GSC, Clarity, Bing WMT). Pattern proven in
 * Desktop/other_web/NewDawnHealth/.mcp.json.
 *
 * Files are env-interpolated (${VAR}) so secrets stay in .env (gitignored).
 * The user fills in real propertyIds / tokens after running `a7seo init`.
 */
export function generatePlatformsScaffold(projectRoot: string): {
  mcp: boolean;
  envExample: boolean;
} {
  const mcpPath = join(projectRoot, '.mcp.json');
  const envExamplePath = join(projectRoot, '.env.platforms.example');

  const mcpConfig = {
    _comment:
      'Generated by `a7seo init`. Per-project MCP server config. Claude Code reads this from cwd, so switching project = switching data source. Add to .gitignore.',
    mcpServers: {
      gsc: {
        type: 'stdio',
        command: 'uvx',
        args: ['mcp-gsc'],
        env: {
          GSC_CREDENTIALS_PATH: '${GOOGLE_SERVICE_ACCOUNT_PATH}',
          GSC_SKIP_OAUTH: 'true',
        },
      },
      ga4: {
        type: 'stdio',
        command: 'uvx',
        args: ['--from', 'google-analytics-mcp', 'ga4-mcp-server'],
        env: {
          GOOGLE_APPLICATION_CREDENTIALS: '${GOOGLE_SERVICE_ACCOUNT_PATH}',
          GA4_PROPERTY_ID: '${GA4_PROPERTY_ID}',
        },
      },
      clarity: {
        type: 'stdio',
        command: 'npx',
        args: ['-y', '@microsoft/clarity-mcp-server'],
        env: {
          CLARITY_API_TOKEN: '${CLARITY_API_TOKEN}',
        },
      },
    },
  };

  const envExample = `# Platform analytics credentials. Copy to .env (gitignored).
# Generated by \`a7seo init\` — see PLATFORMS_SETUP.md or
# Desktop/other_web/NewDawnHealth/.mcp.json for a working reference.

# Google Service Account JSON path (shared across GSC + GA4 MCPs and
# usually shared across all your projects — one SA, multiple property grants).
GOOGLE_SERVICE_ACCOUNT_PATH=

# GA4 — public Measurement ID for client tracking script + numeric Property ID for the API.
VITE_GA4_MEASUREMENT_ID=
GA4_PROPERTY_ID=

# Microsoft Clarity — public Project ID for the client script + Data Export API token (server only).
VITE_CLARITY_PROJECT_ID=
CLARITY_API_TOKEN=

# Bing Webmaster Tools — read by a7seo-mcp's bing_wmt_fetch tool.
BING_WMT_SITE_URL=
BING_WMT_API_KEY=
`;

  let mcpWritten = false;
  let envExampleWritten = false;

  if (!existsSync(mcpPath)) {
    writeFileSync(mcpPath, JSON.stringify(mcpConfig, null, 2) + '\n', 'utf-8');
    mcpWritten = true;
  }

  if (!existsSync(envExamplePath)) {
    writeFileSync(envExamplePath, envExample, 'utf-8');
    envExampleWritten = true;
  }

  return { mcp: mcpWritten, envExample: envExampleWritten };
}

function getPublisherConfig(adapter: string): Record<string, string> {
  switch (adapter) {
    case 'blogposts-ts':
      return {
        blogPostsPath: './data/blogPosts.ts',
        imagesDir: './public/images',
      };
    case 'wordpress':
      return {
        apiUrl: 'https://your-site.com/wp-json/wp/v2',
        username: '',
        applicationPassword: '',
      };
    case 'markdown-files':
    default:
      return {
        outputDir: './content',
      };
  }
}
